Repository Flysoft-Studio/QQNTim, pull requests merged in 2023-07, with the labels that each got.

#65 release 1.3.2
  package.json
Labels: version release

#94 feat(builtins/settings): add basic settings ui
  build.ts
  package.json
  publish/_/install.ps1
  publish/_/uninstall.ps1
  publish/install.sh
  publish/uninstall.sh
  rome.json
  scripts/dev.sh
  scripts/start.sh
  src/builtins/settings/package.json
  src/builtins/settings/publish/qqntim.json
  src/builtins/settings/publish/style.css
  src/builtins/settings/src/_renderer.tsx
  src/builtins/settings/src/components/nav.tsx
  src/builtins/settings/src/components/panel.tsx
  src/builtins/settings/src/consts.ts
  src/builtins/settings/src/main.ts
  src/builtins/settings/src/renderer.ts
  src/config.ts
  src/env.d.ts
  src/globalVar.ts
  src/ipc.ts
  src/loader.ts
  src/main/api/index.ts
  src/main/compatibility/index.ts
  src/main/config.ts
  src/main/debugger.ts
  src/main/loader.ts
  src/main/main.ts
  src/main/patch.ts
  src/main/plugins.ts
  src/ntVersion.ts
  src/plugins.d.ts
  src/renderer/api/app.ts
  src/renderer/api/browserWindow.ts
  src/renderer/api/getVueId.ts
  src/renderer/api/index.ts
  src/renderer/debugger.ts
  src/renderer/loader.ts
  src/renderer/main.ts
  src/renderer/patch.ts
  src/typings/electron.d.ts
  src/typings/index.d.ts
  src/typings/package.json
  src/watch.ts
  tsconfig.json
  yarn.lock
Labels: ⚙功能, ❗需注意, 🖥️不工作: Windows

#120 feat(builtins/settings): support managing plugins
  build.ts
  src/builtins/settings/package.json
  src/builtins/settings/publish/style.css
  src/builtins/settings/src/_renderer.tsx
  src/builtins/settings/src/consts.ts
  src/builtins/settings/src/installer.ts
  src/builtins/settings/src/nav.tsx
  src/builtins/settings/src/panel.tsx
  src/builtins/settings/src/utils.ts
  src/ipc.ts
  src/main/config.ts
  src/main/patch.ts
  src/main/plugins.ts
  src/renderer/api/app.ts
  src/renderer/api/browserWindow.ts
  src/renderer/api/dialog.ts
  src/renderer/api/index.ts
  src/renderer/api/nt/call.ts
  src/renderer/api/nt/index.ts
  src/renderer/api/nt/interrupt.ts
  src/renderer/api/nt/media.ts
  src/renderer/main.ts
  src/typings/index.d.ts
  src/watch.ts
  yarn.lock
Labels: ⚙功能, 🖥️未测试: Windows

#125 feat(renderer/api/nt): get user info by uid
  examples/NT-API/qqntim.json
  examples/NT-API/renderer.js
  src/renderer/api/nt/index.ts
Labels: ⚙功能, 🖥️未测试: Windows

#126 fix(renderer/loader): stylesheets may not be loaded sometimes
  src/renderer/api/index.ts
  src/renderer/api/waitForElement.ts
  src/renderer/api/windowLoadPromise.ts
  src/renderer/loader.ts
Labels: 🪲bug

#128 docs: detailed user guide and development guide, closes https://github.com/Flysoft-Studio/QQNTim/issues/91
  .github/qqntim-plugin-management-page.png
  .github/qqntim-settings-page.png
  .github/settings-entry.png
  DEVELOPMENT.md
  MANUAL.md
  README.md
  src/typings/index.d.ts
Labels: 📖️文档

#132 fix: fix LiteLoaderQQNT compatibility, closes https://github.com/Flysoft-Studio/QQNTim/issues/123
  package.json
  src/main/compatibility/liteloader.ts
  src/main/patch.ts
  src/renderer/api/index.ts
  src/renderer/api/nt/index.ts
  src/renderer/api/nt/media.ts
  src/renderer/api/nt/watcher.ts
  src/renderer/loader.ts
  src/renderer/main.ts
  yarn.lock
Labels: 🪲bug, 💣️兼容性

#143 feat(builtins/settings): add plugin version
  src/builtins/settings/src/utils.ts
  src/typings/index.d.ts
Labels: ⚙功能, 🛠️wip

#165 feat: support custom settings page, closes https://github.com/Flysoft-Studio/QQNTim/issues/161, https://github.com/Flysoft-Studio/QQNTim/issues/160
  examples/NT-API/consts.js
  examples/NT-API/qqntim.json
  examples/NT-API/renderer.js
  examples/NT-API/settings.js
  publish/install.sh
  publish/uninstall.sh
  scripts/start.sh
  src/builtins/settings/src/_renderer.tsx
  src/builtins/settings/src/exports/components.tsx
  src/builtins/settings/src/exports/index.ts
  src/builtins/settings/src/nav.tsx
  src/builtins/settings/src/panel.tsx
  src/common/patch.ts
  src/main/api.ts
  src/main/config.ts
  src/main/patch.ts
  src/renderer/api/index.ts
  src/renderer/patch.ts
  src/typings/index.d.ts
Labels: ⚙功能, 🧩️插件相关, 💿区域: 安装脚本, 📑️区域: 开发脚本, 🧩️区域: 内置插件, 🔌区域: API, 💉️区域: 注入

#167 fix: cannot open LiteLoader settings page, closes https://github.com/Flysoft-Studio/QQNTim/issues/164
  src/builtins/settings/src/nav.tsx
  src/builtins/settings/src/panel.tsx
  src/builtins/settings/src/utils/hooks.tsx
  src/renderer/vueHelper.ts
  src/typings/index.d.ts
Labels: 🪲bug, 💣️区域: 兼容性, 🧩️区域: 内置插件

#170 feat: support printing objects from renderer process, closes https://github.com/Flysoft-Studio/QQNTim/issues/162
  src/common/console.ts
  src/common/ipc.ts
  src/main/patch.ts
  src/renderer/main.ts
  src/renderer/patch.ts
Labels: ⚙功能, 💉️区域: 注入

#171 fix: fix various bugs
  publish/_/install.ps1
  src/builtins/settings/src/panel.tsx
  src/common/ipc.ts
  src/common/utils/console.ts
  src/common/utils/process.ts
  src/common/watch.ts
  src/main/patch.ts
  src/renderer/patch.ts
Labels: 🪲bug, 💿区域: 安装脚本

#180 feat: improve node_modules size and make installation faster
  .github/workflows/build.yml
  build.ts
  package.json
  publish/_/install.ps1
  publish/_/uninstall.ps1
  publish/install.sh
  publish/uninstall.sh
  scripts/pack.ps1
  scripts/pack.sh
  scripts/start.ps1
Labels: ⚙功能, 💿区域: 安装脚本, 📑️区域: 开发脚本

#187 fix(install): dev builds cannot be installed
  publish/_/install.ps1
  publish/_/uninstall.ps1
  publish/install.sh
  publish/uninstall.sh
Labels: 🪲bug, 🖥️未测试: Windows, 💿区域: 安装脚本

#195 增加了macOS的安装脚本，并且更新了使用手册中有关macOS安装的部分
  MANUAL.md
  publish/install_macos.sh
  publish/uninstall_macos.sh
Labels: ⚙功能, 💿区域: 安装脚本

#205 feat(install): change implementation of patching
  publish/_/install.ps1
  publish/_/uninstall.ps1
  publish/install.sh
  publish/install_macos.sh
  publish/uninstall.sh
  publish/uninstall_macos.sh
Labels: 🪲bug, ⚙功能, 🖥️未测试: Windows, 💿区域: 安装脚本
